version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: basestudent
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./demo-enset-student
      dockerfile: Dockerfile
    ports:
      - "8021:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/basestudent
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql
    volumes:
      - backend_data:/data

  frontend:
    build:
      context: ./frontend-angular
      dockerfile: Dockerfile
    ports:
      - "88:80"
    depends_on:
      - backend

volumes:
  mysql_data:
  backend_data:
